# 应用服务 WEB 访问端口
server-port: &port 8081
#服务器地址（后面可能用到，不用修改）
serveUrl: &serveUrl http://localhost:8081
#文件存储地址（后面可能用到，不用修改）
filePath: &filePath SecondClass/src/main/resources/static
#数据库配置
mysql-url: &url jdbc:mysql://localhost:3306/secondclass?useSSL=false&amp&serverTimezone=UTC&allowPublicKeyRetrieval=true
mysql-username: &username root
mysql-password: &password 13824101958
#静态资源地址
static-locations: &static file:D:/javaide/SecondClass/src/main/resources/static
self-attachment: D:\software\IntelliJ IDEA 2022.2.3\IdeaProjects\SecondClass\sc-api\src\main\resources\selfEnclosure\

myConfig:
  #服务器地址
  serveUrl: *serveUrl
  #文件存储地址
  filePath: *filePath

# 应用服务 WEB 访问端口
server:
  port: *port

# spring
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: *url
      username: *username
      password: *password
      db-type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  web:
    #静态资源地址
    resources:
      static-locations: *static
  jackson:
    #json处理忽略空字段
    default-property-inclusion: non_null

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: satoken
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 60
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt秘钥
  jwt-secret-key: F54EFHAfs34fWuSGs2jZWbYfwFE4H6KSE